### ISSUE TITLE
TypeError: scatter_add() takes from 2 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by mane2shar** [harvardnlp/botnet-detection#12]
Traceback (most recent call last):
  File ".\train_botnet.py", line 270, in <module>
    scheduler, logger)
  File ".\train_botnet.py", line 138, in train
    x = model(batch.x, batch.edge_index)
  File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\tusha\Downloads\botnet-detection\botdet\models_pyg\gcn_model.py", line 129, in forward
    xo = net(x, edge_index, edge_attr, deg, edge_weight, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\tusha\Downloads\botnet-detection\botdet\models_pyg\gcn_model.py", line 220, in forward
    xo = self.gcn(x, edge_index, edge_attr, deg, edge_weight, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\tusha\Downloads\botnet-detection\botdet\models_pyg\gcn_base_models.py", line 240, in forward
    x = scatter_(self.aggr, x_j, edge_index[1], dim_size=x.size(0))
  File "C:\Users\tusha\Downloads\botnet-detection\botdet\models_pyg\common.py", line 56, in scatter_
    out = op(src, index, 0, out, dim_size, fill_value)

**Comment by mane2shar** [comment]
Already provided solution, I forgot to check.
