### ISSUE TITLE
2536 Killed  

### ISSUE THREAD

**Issue by TruongDuyLongPTIT** [harvardnlp/botnet-detection#21]
Hi, i need your help.
I already buy colab pro with 25gb ram. But it not enought to train model. Do you have solution for this issue?
Thank you!

**Comment by jzhou316** [comment]
Hi, it would be helpful if you could provide more detailed error message, so that we can see where the program errors out in the code exactly.

**Comment by TruongDuyLongPTIT** [comment]
Hi, tks for your reply but it no error message, it show like above and stop.

**Comment by TruongDuyLongPTIT** [comment]
Do you provide a jupyter notebook? I spend 3 days to run this project, but have no result. I am very grateful if you provide a jupyter notebook.

**Comment by TruongDuyLongPTIT** [comment]
https://github.com/TruongDuyLongPTIT/DoAnTotNghiepPTIT/blob/main/Untitled1.ipynb
You can see error here.

**Comment by jzhou316** [comment]
In the installation, can you specify the version of pytorch scatter to be a previous one by `pip install torch-scatter=1.3.1`? There is a known issue with the newest version for our code.

**Comment by TruongDuyLongPTIT** [comment]
When i install torch-scatter=1.3.1 then this happen:
Traceback (most recent call last):
  File "/content/botnet_detection/train_botnet.py", line 12, in <module>
    from botdet.models_pyg.gcn_model import GCNModel
  File "/content/botnet_detection/botdet/models_pyg/gcn_model.py", line 4, in <module>
    from .gcn_base_models import NodeModelAdditive, NodeModelMLP
  File "/content/botnet_detection/botdet/models_pyg/gcn_base_models.py", line 5, in <module>
    from torch_geometric.nn.inits import glorot, zeros
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/usr/local/lib/python3.7/dist-packages/torch_sparse/__init__.py", line 40, in <module>
    from .storage import SparseStorage  # noqa
  File "/usr/local/lib/python3.7/dist-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
ImportError: cannot import name 'segment_csr' from 'torch_scatter' (/usr/local/lib/python3.7/dist-packages/torch_scatter/__init__.py)

**Comment by TruongDuyLongPTIT** [comment]
I think "Killed" happen because it take a lot of ram. Do you have some ways to save ram?

**Comment by TruongDuyLongPTIT** [comment]
when i run !dmseg. It show me it is killed because out of memory. I have 25Gb ram, and it not enough. I think you code have a problem about load data to ram
[ 5504.567657] Memory cgroup out of memory: Killed process 55997 (python3) total-vm:32736176kB, anon-rss:24958644kB, file-rss:76852kB, shmem-rss:12288kB, UID:0 pgtables:51400kB oom_score_adj:0
[ 5505.200038] oom_reaper: reaped process 55997 (python3), now anon-rss:0kB, file-rss:74732kB, shmem-rss:12288kB
[ 5565.818167] printk: dmesg (59088): Attempt to access syslog with CAP_SYS_ADMIN but no CAP_SYSLOG (deprecated).

**Comment by jzhou316** [comment]
The graph data is big so you need bigger RAM. However, if it is the RAM size that causes the problem, you can load the data on demand instead of loading it all at once to RAM. This can be down via setting `in_memory=False` [here](https://github.com/harvardnlp/botnet-detection/blob/1c55412debb61a6a3ac30085f0b515101e1bffca/train_botnet.py#L24) (you could also use smaller batch size). Also you may find some of the discussions [here](https://github.com/harvardnlp/botnet-detection/issues/8#issuecomment-874197844) be helpful.

**Comment by TruongDuyLongPTIT** [comment]
Many thank for your support. I have solved this problem by comment model.to(device) then train it by TPUs in Colab. TPU in colab has 35GB ram (GPU just have 25Gb). So i train it successful. But i dont understand when you say use smaller batch size, because batch size in your code is just 2. I think it is smallest batch size so can not decrease it. 
And i have an other problem, even i train with TPU but each epoch take about 1hour. And can can not train all 50 epoch. Do you have some tips to train fastter? (I using batch size = 2, 8, 16 but time do not improve)

**Comment by TruongDuyLongPTIT** [comment]
I have solved problem about run time. When i train it by TPU with batch size = 64, it take about 45 minute each epoch.
But when I train it with GPU instead TPU with batch_size = 16, each epoch just take about 2 minute. 
So i guess pytorch only should train on GPU (not TPU).
Even when i train with TPU, f1 score and recall always = 0. But train with GPU (same code) recall anced f1 score seem more correcly. I dont know why train by difference hardware provide difference result =))

**Comment by jzhou316** [comment]
Sounds good. I have never run it on TPU so your input is valuable; there might be some thing that needs to be customized to TPU  as you suggested.
